---
title: "User Progression"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
    orientation: rows
    horizontal_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
players <- read.csv("Player_Prog.csv")
pacman::p_load(tidyverse,plotly,flexdashboard)
```

Total Users
=======================================================================

Row
-----------------------------------------------------------------------

### Total Starts
```{r}
p1 <- players %>% 
  ggplot(aes(Checkpoint,total_start))+
  geom_line(group=1,color="orange")+
  theme_light ()+
    theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+
    xlab("")+ylab("")
ggplotly(p1)
```

Row
-----------------------------------------------------------------------

### Total Fails 
```{r}
p2 <- players %>% 
  ggplot(aes(Checkpoint,total_fail))+
  geom_line(group=1,colour="red")+
  theme_light()+
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+xlab("")+ylab("")
ggplotly(p2)
```

Row
-----------------------------------------------------------------------

### Total Quits
```{r}
p3 <- players %>% 
  ggplot(aes(Checkpoint,total_quit))+
  geom_line(group=1,colour="purple")+
  theme_light()+
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+xlab("Checkpoint")+ylab("")
ggplotly(p3)
```

Unique Users
=======================================================================

Row
-----------------------------------------------------------------------

### Unique Users
```{r}
p4 <- players %>% 
  ggplot(aes(Checkpoint,usercount))+
  geom_line(group=1,color="orange")+
  theme_light ()+
    theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+
    xlab("")+ylab("")
ggplotly(p4)
```

Row
-----------------------------------------------------------------------

### Unique User Fails
```{r}
p5 <- players %>% 
  ggplot(aes(Checkpoint,unique_user_fail))+
  geom_line(group=1,colour="red")+
  theme_light()+
    theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+
      xlab("")+
  ylab("")
ggplotly(p5)
```

Row
-----------------------------------------------------------------------

### Unique User Quits
```{r}
p6 <- players %>% 
  ggplot(aes(Checkpoint,unique_user_quit))+
  geom_line(group=1,colour="Purple")+
  theme_light()+
    theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))+
      xlab("Checkpoint")+
  ylab("")
ggplotly(p6)
```

